### ISSUE TITLE
Able to steer car across the track without accelerating!?

### ISSUE THREAD

**Issue by gingerbeardman** [Foppygames/max-downforce#5]
I was just starting my first race and moved my car left of the mountain track into the abyss before I even start accelerating. 

So I think turning should only be possible when accelerating. 

> You could go one step further and allow slower turning at slow speeds and full turning rate only after a certain high speed, ramping the rate in between those two.

Also, just to say the smoothness, frame rate, and attention to detail in this game is excellent. Thanks for making it!

**Comment by Foppygames** [comment]
Thank you for raising this issue and you are right that this is a bit strange. However, I found that only allowing for left/right movement when going forward could lead to situations where the car gets stuck against a road side object. So this sliding left/right was left in as an easy fix to this problem. (I feel there is an application for this in the real world!)
